# Generated by Django 5.2 on 2025-08-08 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_alter_image_position'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['position'], name='places_imag_positio_b2104b_idx'),
        ),
    ]
