# Generated by Django 5.2 on 2025-08-12 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_image_places_imag_positio_b2104b_idx'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='description_long',
            new_name='long_description',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='description_short',
            new_name='short_description',
        ),
    ]
